### ISSUE TITLE
Multiple screen capture

### ISSUE THREAD

**Issue by trookie2000** [w3c/mediacapture-screen-share#292] opened 2023-12-27 13:15 UTC
provide the user with a media selector with checkbox-like functionality,maybe the user can choose any N tabs, any N windows, or any N monitors, but not a combination of K tabs and N-K screens.How do I write the code to implement this functionality
The current API (the navigator. MediaDevices. GetDisplayMedia) cannot achieve the multiple capture.
![image](https://github.com/w3c/mediacapture-screen-share/assets/109945614/04179eca-c945-4db9-9e4d-8ba507b0bd0f)

**Comment by eladalon1983** [comment] 2024-01-02 10:16
This looks like a duplicate of https://github.com/w3c/mediacapture-screen-share-extensions/issues/8, and even uses a mock image which was produced specifically for that issue and first posted there. Should we not just continue the discussion there? (Or alternatively, this could be suggested in the [Screen Capture Community Group](https://www.w3.org/community/sccg/), possibly in its [Discussions repo](https://github.com/screen-share/discuss).)

**Comment by jan-ivar** [comment] 2024-01-09 17:50
Closing as a dup of https://github.com/w3c/mediacapture-screen-share-extensions/issues/8.

**Closed as completed by jan-ivar** 2024-01-09 17:50 UTC
