### ISSUE TITLE
Should we support audio?

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-screen-share#69] opened 2018-08-24 19:16 UTC
"1. Introduction" says that the document says is primarily concerns itself with video, but that the general mechanism here could be extended to audio and depth.

Does this mean we should ignore audio:true or define what to do in this case?
If we want to support audio we should support MediaTrackConstraints (#67).

If we support audio I think we should make it simple, and either share all audio being played out or none of it. Filtering out audio on a per-window basis does not make sense the way that display medias do. I think it would confuse the user as to what is or is not shared and have no practical uses.

We could also not support audio, in which case we should decide whether to ignore it or throw an exception, we need to be consistent (#68).

**Comment by uysalere** [comment] 2018-08-29 21:12
There is already some discussion on #61 about this.

**Comment by aboba** [comment] 2018-08-30 05:36
Remember that it is the user that selects what is to be shared.  What happens if the user selects a window or a particular display? It would not be appropriate to share audio from other windows or displays which were not selected  (by sharing all audio).

**Comment by alvestrand** [comment] 2018-08-30 14:21
I think this is a duplicate of #61. Closing as dup.

**Closed as completed by alvestrand** 2018-08-30 14:21 UTC
Labels: September 2018 Virtual Interim
