### ISSUE TITLE
Add configuration to chose whether or not to focus/bring to front the shared window display surface

### ISSUE THREAD

**Issue by LukasKalbertodt** [w3c/mediacapture-screen-share#138] opened 2020-04-28 11:22 UTC
I wondered why the windows that I share via `getDisplayMedia` are suddenly in focus and in front of all other windows. This is done by Firefox and Chrome. I [asked on StackOverflow](https://stackoverflow.com/q/60172910/2408867) and got this as an answer:

> The rationale is the typical use case is someone presenting a document in a web conference call. In that context, the assumption is that since this is a user-initiated action (it requires a user gesture), the user intends to interact with the surface that they just shared.
>
> [...]
>
> If you have a compelling use case where this is problematic, consider describing it in a new issue on the specification.

So here I am. While I understand that this specification was developed with web conferences as important use case, I think the behavior of bringing the shared window to the front is not helpful in other situations. Let me motivate my use case:

I am developing a web application which allows users to very easily record their screen, camera and voice ([repository link](https://github.com/elan-ev/opencast-studio), in case you're interested). The application is targeted mostly at *technically-inexperienced* lecturers at universities and in other educational contexts. Our main goal is to make it *as easy as possible* to record lectures for your students. Due to COVID-19, lots of universities and lecturers got very interested in this and are now actively using it.

The web application works by first selecting your video input, then inspecting the preview to check if everything is correct, then selecting audio input, and only then to record. In this situation, the current behavior of bringing the shared windows to the front is very confusing to many users. Some users already suggested we add a big warning/notice in our application to explain to the users that the window will be focused and that they have to switch to the browser again. But this seems like a not-great workaround. 

**So my suggestion is**: let the web application decide whether or not the browser focuses the newly shared window.

I am not sure how this would fit into the API -- I am not particularly experienced with JS APIs. It seems like it could be a field in the `MediaStreamConstraints`. I don't think it makes sense as part of the `MediaTrackConstraints`, right?

**Comment by guest271314** [comment] 2020-05-07 04:35
A prospective non-workaround UI solution that could be incorporated into the specifcation and existing prompt dialogs would be to include a checkbox option "Focus on captured Window or Screen" default value checked, which is current intended behaviour, beneath "Remember this decision" 
![Screenshot_2020-05-07_04-23-23](https://user-images.githubusercontent.com/4174848/81254689-5acb2180-901b-11ea-8893-ad7a8241ea48.png).

"The user agent [must; should] provide the user the option to retain focus at the window that calls getDisplayMedia()."

**Comment by guest271314** [comment] 2020-05-07 06:25
Workaround for Chromium 81 (stable) which does gain focus when `prompt()` is used and the screen selected is an application. Firefox doe not gain focus using the same code. 

```
const retainFocus = true;
onclick = async _ => {
 onclick = null;
 const stream = await navigator.mediaDevices.getDisplayMedia({video: true});
 if (retainFocus) {
   prompt('Retain focus', 'Ok');
 };
};
```

**Comment by guest271314** [comment] 2020-05-11 00:29
Perhaps due to unintended consequences, this breaks `.select()` and `.focus()` at Firefox. Can't select  and gain focus on `<input>` or `<texarea>` elements or focus `opener` from an opened `window` programmatically.

**Comment by guest271314** [comment] 2020-05-11 01:53
At Firefox 76 `requestFullScreen()` can be used to _not_ focus on the captured application.

```

onclick = e => {
  onclick = null;
  navigator.mediaDevices.getDisplayMedia({video: true})
  .then(async stream => {
      await document.documentElement.requestFullscreen();
  });
}
```

That is, when an error is not thrown denying fullscreen access because `requestFullScreen()` is not called inside a short-running event handler. 


```
Request for fullscreen was denied because Element.requestFullscreen() was not called from inside a short running user-generated event handler.
TypeError: Fullscreen request denied
```

That occurred only twice out of at least 20 attempts, the first time not on purpose, the second time waiting an extra second before selecting the text editor application.

At Firefox 78 `requestFullscreen()` just throws an error

```
Request for fullscreen was denied because requesting element is not in the currently focused tab. firefox
TypeError: Fullscreen request denied
```

Focusing by default on the application that is a text editor has particular issues: it is not possible to regain focus on the document programmatically at that point. The cursor is in the text  editor application, not the `window` and not the `document`, resulting in `<input>.select()` and `<textarea>.focus()` and `opener.focus()` not working at all. Is that by design?

**Comment by henbos** [comment] 2020-10-08 14:45
Let's specify a default value and add a constraint.

**Comment by henbos** [comment] 2020-10-08 14:48
Actually there is still some disagreement about whether or not we need a constraint versus always consistently doing the same thing, so more discussion needed, but we all agree we should specify the default

**Comment by henbos** [comment] 2020-10-08 14:49
Defaulting to what is done by both implementations today makes sense. Safari does not support window capture yet, and can follow.

**Comment by happylinks** [comment] 2020-10-11 18:42
Also running into this problem for tella.tv. Ideally we could disable giving initial focus but potentially give focus later? That way you can finish configuring your setup first, click Record in the app and then we’d call mediaStream.focus() or something to take the user to the window they shared.
The current behavior is confusing our users a lot; they think they’re already recording when they’re not.
Is this being discussed somewhere else than this thread? Would love to follow/join the conversation.

**Comment by amiregelz** [comment] 2020-12-29 09:58
Running into this issue as well. Working on a web app that allows multiple screen shares and want users to be able to select several screens without the focus & context changing every time they choose a screen.
It would be really cool to be able to choose whether to enable/disable this initial auto focus in the getDisplayMedia API.
It can be even cooler if we could have an option to potentially give focus to the shared screen later, like @happylinks suggested.
@henbos What's the status of this? Is there any update?

**Comment by eladalon1983** [comment] 2021-05-25 20:01
See issue #165. Possibly we can merge these discussions? I am not sure what discussions took place in October 2020, but at the moment Chrome is considering conditional focus, so it's unclear if we'd be able to support the specification of default value and calling it a day. (If we will - unclear which value we'd want, switch-focus or don't.)

**Comment by eladalon1983** [comment] 2021-05-26 11:37
Duplicate of #165; closing.

**Closed as completed by eladalon1983** 2021-05-26 11:37 UTC
Labels: Ready for PR
