### ISSUE TITLE
Screenshot (still image) capability 

### ISSUE THREAD

**Issue by inexorabletash** [w3c/mediacapture-screen-share#107] opened 2019-05-14 23:00 UTC
This is hinted at in #105 but there's a request against Chrome (https://crbug.com/962538) to provide single-image capture. Obviously, it is possible with this API to get a stream and take a single image from it. But the user prompt will likely be confusing since the intent isn't clear - it will necessarily indicate something like  "share your screen"

I could imagine a way to a variant of the API that provided a single frame, and allowed the browser to provide a more scoped message.

This is hinted at in #105 but I didn't find a specific feature request. Apologies if this has been discussed before.

**Comment by guest271314** [comment] 2019-05-16 00:30
@inexorabletash Does the "MediaStream Image Capture" https://www.w3.org/TR/image-capture/ (https://github.com/w3c/mediacapture-image/blob/gh-pages/implementation-status.md) not provide means to achieve the requirement?

(See also https://bugs.chromium.org/p/chromium/issues/detail?id=838108 Chromium `ImageBitmapRenderingContext` bug, e.g., `.grabFrame()`)

**Comment by guest271314** [comment] 2019-05-16 09:49
An attempt to meet the requirement 

`const blob = await screenShot(document.body, { type: 'png'  })`

described at the linked Chrome issue using existing browser API; i.e., capturing only a specific element [("#Specifications") at MDN `Image​Capture​.take​Photo()` documentation ("display")](https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture/takePhoto#Specifications) from a document at the same domain [MDN Web Docs ("controller")](https://developer.mozilla.org/en-US/) using existing browser functionality. 

At media capture "display" document; e.g., 
```
// signaling; e.g., window.postMessage(); MessageChannel; SharedWorker
const bc = new BroadcastChannel("getDisplayMediaImageCapture");
bc.addEventListener("message", e=>{
    const element = document.getElementById(e.data.id);
    const {left, top: _top, width, height} = element.getBoundingClientRect();
    const handleMediaCaptureScrollIntoView = e => {
      if (element.getBoundingClientRect().top < 1) {
        bc.postMessage({
          width,
          height
        });
        window.removeEventListener("scroll", handleMediaCaptureScrollIntoView);
      }
      console.log(e);
    }

    window.addEventListener("scroll", handleMediaCaptureScrollIntoView);
    window.scrollTo({
        left,
        top: _top,
        behavior: "smooth"
    });
});
```

At media capture "controller" document

```
(async()=>{
    const mediaStream = await navigator.mediaDevices.getDisplayMedia({video:true});
    const [videoTrack] = mediaStream.getVideoTracks();
    const img = new Image;
    document.body.appendChild(img);
    const bc = new BroadcastChannel("getDisplayMediaImageCapture");
    bc.addEventListener("message", async e => {
      const {width, height} = e.data;
      console.log(width, height);
      const imageCapture = new ImageCapture(videoTrack);
      const osc = new OffscreenCanvas(width, height);
      const osctx = osc.getContext("2d");
      const imageBitmap = await imageCapture.grabFrame();
      osctx.drawImage(imageBitmap, 0, 0);
      img.src = URL.createObjectURL(await osc.convertToBlob({type:"image/png"}));
      videoTrack.enabled = false;
      videoTrack.stop();
      imageBitmap.close();         
    }, {once: true});
    bc.postMessage({"id":"Specifications"});    
}
)();

```

Resulting image

![getDisplayMediaAttemptToCaptureSpecificElementAsScreenShot](https://user-images.githubusercontent.com/4174848/57844048-d0acfc00-77be-11e9-98fe-72021d9d99b6.png)

This feature request,  and further, the ability to set an HTML element to be captured as a _device_ or _window_ or _application_, both as a still image and as a live stream (e.g., `<video>` irrespective of changes to `src` element) has several use cases and spans several domains; including, but not limited to, education; software and hardware testing; general media creation and post-production.

**Comment by jordanaustin** [comment] 2019-05-23 06:05
@guest271314 First of all, thank you for this example! 

The main issue has never really been the ability with the getDisplayMedia API, this is an amazingly powerful API. The issue always comes down to the UI when invoking getDisplayMedia({video:true}), the UI you're presented with is a share screen UI which doesn't at all fit what I'm trying to do which is the ImageCapture portion. See the UI below that is the issue. 

<img width="634" alt="Screen Shot 2019-05-22 at 10 48 12 PM" src="https://user-images.githubusercontent.com/709038/58228895-f0738100-7ce4-11e9-8eb0-da9b316def3b.png">

I'm looking for a more targeted permission UI for a single frame image capture UI so that it isn't confusing to users.

**Comment by guest271314** [comment] 2019-05-23 14:10
@jordanaustin Before executing `getDisplayMedia()` you could provide a notification to the user that the captured screen will be used only for a single still image, and advise the user to select "**Chrome Tab**", which sets the focus to the selected tab (useful when the captured `window` created by `window.open()`), then notify the user when the `MediaStreamTrack` `enabled` property is set to `false` and `stop()` is called. At the example, `.close()` should also be executed on the `BroadcastChannel` (or other messaging API) instance.

**Comment by jordanaustin** [comment] 2019-05-28 19:20
> @jordanaustin Before executing `getDisplayMedia()` you could provide a notification to the user that the captured screen will be used only for a single still image, and advise the user to select "**Chrome Tab**", which sets the focus to the selected tab (useful when the captured `window` created by `window.open()`), then notify the user when the `MediaStreamTrack` `enabled` property is set to `false` and `stop()` is called. At the example, `.close()` should also be executed on the `BroadcastChannel` (or other messaging API) instance.

I agree with you, we _could_ do this, but as you can see this is far from ideal. It seems to make sense that we should distinguish between the two types of actions we're trying to do and provide the appropriate user permission UI.

The whole goal for this request isn't to find a work-around that developers need to implement in order to inform their users how to use the this feature. Rather my goal is to have targeted browser UI that matches the action the user is trying to perform. Asking a user to share a stream of your screen could be very scary to a user that's just clicked a button to capture a screenshot. But asking for permission to capture a screenshot when the user clicks that same button is far less scary IMO.

**Comment by guest271314** [comment] 2019-05-29 00:49
@jordanaustin 

> The whole goal for this request isn't to find a work-around that developers need to implement in order to inform their users how to use the this feature. 

Have found that creating, if possible, multiple different workarounds provides a means to locate additional bugs in an API, template basic UI's if needed, for the ability to describe how the procedure should ideally work in code.

For example, consider the specific timing of granting of permission to take a screen shot in relation to when the screenshot is actually copied from the screen. 

While trying to reproduce an unrelated bug using `getDisplayMedia()` recorded (using `MediaRecorder`) two versions of the code run with output at `console`. However, instead of the UI being closed before the first image is captured, the permission UI covering a substantial portion of the screen, is captured. Would the user expect the permissions UI to be captured as an image as the first frame? Without trying to create workarounds this screenshot proposal could become an API which captured the permission UI because no workarounds, directly relating to the prospective UI improvements, or related code which presents issues which could affect this screen shot API; that is, making certain that a screen shot does not mean capturing the permission UI as the first frame. What should the UI for a screen shot API look like and do - and not look like and not do?

**Comment by guest271314** [comment] 2019-05-31 01:56
@jordanaustin The user is technically sharing one frame of a media stream of their screen. The developer can suggest that to capture the contents of the HTML `document` loaded in a `window` to select "Chrome tab". If the element to be captured is the first child of `document.body` the `scrollTo()` call will not be necessary, as the element should be positioned at `top:0` and `left:0`, which can also be achieved by using `document.body.insertAdjacentElement("afterbegin", element)`.

> Asking a user to share a stream of your screen could be very scary to a user that's just clicked a button to capture a screenshot. But asking for permission to capture a screenshot when the user clicks that same button is far less scary IMO.

What is the difference between capturing a single screen shot (one image captured from a `MediaStreamTrack`) and capturing multiple screen shots (more than one image being captured from a `MediaStreamTrack`)?

> The whole goal for this request isn't to find a work-around that developers need to implement in order to inform their users how to use the this feature. Rather my goal is to have targeted browser UI that matches the action the user is trying to perform.

Reliance on specification authors to compose code implemented and shipped in browsers to the exact requirement that is specified in a filed issue might not ever occur, or be implemented differently than expected. The developer can describe the procedure to the user, in detail, including how to navigate the screen capture current UI. Would suggest to create the UI to the specifications mentioned, without waiting on a specification author or authors to write language which will translate into exact implementations at browsers. If the UI is already designed, then there is less room for confusion as to what the complete UI should be displayed as, and what should occur before and after the single image is captured.

Does the solution to this issue also include the video `MediaStreamTrack` being captured and stopped internally in the browser at the first frame (e.g., see https://github.com/w3c/mediacapture-screen-share/issues/108)? Or, will the developer code still call `getDisplayMedia()` and `MediaStreamTrack.stop()` when the screen shot is taken?

**Comment by henbos** [comment] 2019-06-20 14:49
@armax00 I see you're assigned to the crbug, is this of interest to Chrome?

**Comment by armax00** [comment] 2019-06-20 15:26
In my opinion it is the case that the work-arounds proposed are per-se work-arounds. As henbos@ indicated in https://github.com/w3c/mediacapture-screen-share/issues/108 the existing APIs ore not designed for this use case, hence do not look fitting.

I believe there is room for such an API for this use case. What is the opinion of other browser about it? Also, are there different opinions then mine in Chrome?

**Comment by guest271314** [comment] 2019-06-20 23:47
@armax00  

 > What is the opinion of other browser about it? 

The workarounds are just that. 

Already possible at Firefox by several means. Including using Developer Tools to select a specific portion of the screen ![firefox_developer_tools_take_a_screenshot](https://user-images.githubusercontent.com/4174848/56927695-5a24b480-6ac4-11e9-84b5-9255846ee556.png) (https://github.com/w3c/mediacapture-screen-share/issues/105). See also https://github.com/web-platform-tests/wpt/issues/14360; https://searchfox.org/mozilla-central/source/testing/mochitest/tests/SimpleTest/WindowSnapshot.js.

Chromium/Chrome is _far_ behind Firefox in the field of a screenshot API. 

If Chromium does implement this the means to select only portion of the screen should be included in the UI.

**Comment by guest271314** [comment] 2019-06-21 01:56
@armax00 Re Chrome a circa 2017 question Is it possible to take a screenshot at Chromium, Chrome without using a headless instance or an extension? https://stackoverflow.com/q/46882371

**Comment by henbos** [comment] 2019-08-01 14:55
This is the wrong API for screenshot and this working group isn't interested

**Closed as completed** 2019-08-01 14:54 UTC
Labels: question

**Comment by ghawkescs** [comment] 2020-03-20 20:57
@henbos what is the correct API for screenshot that we should look into?

**Comment by aboba** [comment] 2020-03-20 22:12
In general, capturing a frame from a stream is handled by [Canvas](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos).  An historical perspective is available [here](https://stackoverflow.com/questions/4912092/using-html5-canvas-javascript-to-take-in-browser-screenshots).
